### ISSUE TITLE
Needed patch, extern some variables?

### ISSUE THREAD

**Issue by bootchk** [carlobaldassi/gimp-lqr-plugin#5]
It has been reported on the gimp-dev mail list that the following patch is needed.
See https://mail.gnome.org/archives/gimp-developer-list/2020-June/thread.html
I am not the author of the patch, see the thread.

>   --- a/src/interface_I.c.ORIG    2020-06-04 14:10:54.237033228 +0200
 > +++ b/src/interface_I.c    2020-06-04 14:19:20.898005308 +0200
 > @@ -65,13 +65,13 @@
 >
 >   gint dialog_I_response = GTK_RESPONSE_OK;
 >
 > -PlugInUIVals *ui_state;
 > -PlugInVals *state;
 > -PlugInDialogVals *dialog_state;
 > -gboolean features_are_sensitive;
 > +extern PlugInUIVals *ui_state;
 > +extern PlugInVals *state;
 > +extern PlugInDialogVals *dialog_state;
 > +extern gboolean features_are_sensitive;
 >   InterfaceIData interface_I_data;
 >
 > -GtkWidget *dlg;
 > +extern GtkWidget *dlg;
 >   GtkWidget *coordinates;
 >
 >   gulong size_changed = 0;
 > --- a/src/interface_aux.c.ORIG    2020-06-04 14:10:54.237033228 +0200
 > +++ b/src/interface_aux.c    2020-06-04 14:21:52.512996954 +0200
 > @@ -48,11 +48,11 @@
 >
 >   gint dialog_aux_response = GTK_RESPONSE_OK;
 >
 > -PlugInUIVals *ui_state;
 > -PlugInVals *state;
 > -PlugInDialogVals *dialog_state;
 > +extern PlugInUIVals *ui_state;
 > +extern PlugInVals *state;
 > +extern PlugInDialogVals *dialog_state;
 >
 > -GtkWidget *dlg;
 > +extern GtkWidget *dlg;
 >
 >   /***  Public functions  ***/
 >

**Comment by carlobaldassi** [comment]
I have just tried compiling against GIMP 2.10.18 and I see a bunch of deprecations, but no errors. I'm on Linux. Any idea what may be causing this?

**Comment by bootchk** [comment]
No, I don't understand the need for the patch. I am not the author of the patch. I am just relaying what was said on the gimp mail list.  It said there that the patch was for gimp-lqr v0.7.2 (as I recall) which doesn't seem to match with your repository.

**Comment by koiuo** [comment]
@carlobaldassi, 
on Archlinux build started failing for me

```
/usr/bin/ld: interface_I.o:(.bss+0x68): multiple definition of `state'; interface.o:(.bss+0x250): first defined here
/usr/bin/ld: interface_I.o:(.bss+0x60): multiple definition of `dialog_state'; interface.o:(.bss+0x248): first defined here
/usr/bin/ld: interface_I.o:(.bss+0x70): multiple definition of `ui_state'; interface.o:(.bss+0x258): first defined here
/usr/bin/ld: interface_I.o:(.bss+0x10): multiple definition of `dlg'; interface.o:(.bss+0x0): first defined here
/usr/bin/ld: interface_I.o:(.bss+0x58): multiple definition of `features_are_sensitive'; interface.o:(.bss+0x238): first defined here
/usr/bin/ld: interface_aux.o:(.bss+0x8): multiple definition of `dialog_state'; interface.o:(.bss+0x248): first defined here
/usr/bin/ld: interface_aux.o:(.bss+0x10): multiple definition of `state'; interface.o:(.bss+0x250): first defined here
/usr/bin/ld: interface_aux.o:(.bss+0x18): multiple definition of `ui_state'; interface.o:(.bss+0x258): first defined here
/usr/bin/ld: interface_aux.o:(.bss+0x0): multiple definition of `dlg'; interface.o:(.bss+0x0): first defined here
```

I guess the issue may be fresh gimp or related package (gegl, babl, ...). FWIW mine are
```
gimp = 2.10.18-8
gegl = 0.4.22-3
babl = 0.1.74-1
```

**Comment by carlobaldassi** [comment]
Thanks @edio, did you check whether the patch fixes the problem?

**Comment by koiuo** [comment]
Checked just now: yes, the patch helped.

I couldn't apply the patch from the comment though (probably some copy-pasting artifact messing with new lines or whitespaces), so I have turned this into a PR

**Comment by carlobaldassi** [comment]
This should hopefully be fixed now.

**Comment by koiuo** [comment]
Thanks for merging this so quickly!

I am able now to build and install [gimp-plugin-lqr-git](https://aur.archlinux.org/packages/gimp-plugin-lqr-git/) package from aur
